services:
  ai-engine:
    
    build: 
      context: ./gdpr-agent-ai-engine
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} 
    networks:
      - gdpr-network

 
  backend:
    build: 
      context: ./gdpr-agent-backend
    ports:
      - "8080:8080"
    environment:
      - PYTHON_URL=http://ai-engine:5000 
    depends_on:
      - ai-engine 
    networks:
      - gdpr-network

  frontend:
    build: 
      context: ./gdpr-agent-frontend
    ports:
      
      - "80:80" 
    depends_on:
      - backend
    networks:
      - gdpr-network

networks:
  gdpr-network:
    driver: bridge
